-- MySQL Script generated by MySQL Workbench
-- Sat Dec 11 22:31:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Faculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Faculty` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Faculty` (
  `idFaculty` INT NOT NULL,
  `FacultyName` VARCHAR(45) NOT NULL,
  `NumOfDep` INT NOT NULL,
  PRIMARY KEY (`idFaculty`, `FacultyName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Department` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `idDepartment` INT NOT NULL,
  `DepartmentName` VARCHAR(45) NOT NULL,
  `Faculty_idFaculty` INT NOT NULL,
  `Faculty_FacultyName` VARCHAR(45) NOT NULL,
  `DepartmentBudget` INT NOT NULL,
  PRIMARY KEY (`idDepartment`, `DepartmentName`, `Faculty_idFaculty`, `Faculty_FacultyName`),
  INDEX `fk_Department_Faculty1_idx` (`Faculty_idFaculty` ASC, `Faculty_FacultyName` ASC) VISIBLE,
  CONSTRAINT `fk_Department_Faculty1`
    FOREIGN KEY (`Faculty_idFaculty` , `Faculty_FacultyName`)
    REFERENCES `mydb`.`Faculty` (`idFaculty` , `FacultyName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Semester` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Semester` (
  `Year` INT NOT NULL,
  `IsCurrentSemester` TINYINT NOT NULL DEFAULT NA,
  PRIMARY KEY (`Year`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `idCourse` INT NOT NULL,
  `CourseName` VARCHAR(45) NOT NULL,
  `Year` VARCHAR(45) NOT NULL,
  `Elective` TINYINT NULL,
  `Mandatory` TINYINT NULL,
  `Lecturer` VARCHAR(45) NOT NULL,
  `Assistant` VARCHAR(45) NOT NULL,
  `Semester` VARCHAR(45) NOT NULL,
  `Department_idDepartment` INT NOT NULL,
  `Department_DepartmentName` VARCHAR(45) NOT NULL,
  `Semester_Year` INT NOT NULL,
  PRIMARY KEY (`idCourse`, `Department_idDepartment`, `Department_DepartmentName`, `Semester_Year`),
  INDEX `fk_Course_Department1_idx` (`Department_idDepartment` ASC, `Department_DepartmentName` ASC) VISIBLE,
  INDEX `fk_Course_Semester1_idx` (`Semester_Year` ASC) VISIBLE,
  CONSTRAINT `fk_Course_Department1`
    FOREIGN KEY (`Department_idDepartment` , `Department_DepartmentName`)
    REFERENCES `mydb`.`Department` (`idDepartment` , `DepartmentName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Semester1`
    FOREIGN KEY (`Semester_Year`)
    REFERENCES `mydb`.`Semester` (`Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lecturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Lecturer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Lecturer` (
  `idLecturer` INT NOT NULL,
  `LecturerName` VARCHAR(45) NOT NULL,
  `LecturerSurname` VARCHAR(45) NOT NULL,
  `LecturerBirthday` DATE NOT NULL,
  `Faculty` VARCHAR(45) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `Title` VARCHAR(25) NOT NULL,
  `givenLectures` INT NOT NULL,
  `Course_idCourse` INT NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLecturer`, `Course_idCourse`),
  INDEX `fk_Lecturer_Course1_idx` (`Course_idCourse` ASC) VISIBLE,
  CONSTRAINT `fk_Lecturer_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Advisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Advisor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Advisor` (
  `idAdvisor` INT NOT NULL,
  `AdvisorName` VARCHAR(45) NOT NULL,
  `AdvisorSurname` VARCHAR(45) NOT NULL,
  `Faculty` VARCHAR(45) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `Lecturer_idLecturer` INT NOT NULL,
  PRIMARY KEY (`idAdvisor`),
  INDEX `fk_Advisor_Lecturer1_idx` (`Lecturer_idLecturer` ASC) VISIBLE,
  CONSTRAINT `fk_Advisor_Lecturer1`
    FOREIGN KEY (`Lecturer_idLecturer`)
    REFERENCES `mydb`.`Lecturer` (`idLecturer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Club` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Club` (
  `idClub` INT NOT NULL,
  `ClubName` VARCHAR(45) NOT NULL,
  `Year` VARCHAR(45) NOT NULL,
  `NumOfMember` INT NOT NULL,
  PRIMARY KEY (`idClub`, `ClubName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `idStudent` INT NOT NULL,
  `StudentName` VARCHAR(45) NOT NULL,
  `StudentSurname` VARCHAR(45) NOT NULL,
  `StudentBirthday` DATE NOT NULL,
  `Faculty` VARCHAR(45) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `Scholarship` VARCHAR(45) NULL,
  `GPA` DECIMAL(2) NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `Advisor_idAdvisor` INT NOT NULL,
  `Club_idClub` INT NOT NULL,
  `Club_ClubName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStudent`, `Advisor_idAdvisor`),
  INDEX `fk_Student_Advisor1_idx` (`Advisor_idAdvisor` ASC) VISIBLE,
  INDEX `fk_Student_Club1_idx` (`Club_idClub` ASC, `Club_ClubName` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Advisor1`
    FOREIGN KEY (`Advisor_idAdvisor`)
    REFERENCES `mydb`.`Advisor` (`idAdvisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Club1`
    FOREIGN KEY (`Club_idClub` , `Club_ClubName`)
    REFERENCES `mydb`.`Club` (`idClub` , `ClubName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assistant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Assistant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Assistant` (
  `idAssistant` INT NOT NULL,
  `AssistantName` VARCHAR(45) NOT NULL,
  `AssistantSurname` VARCHAR(45) NOT NULL,
  `AssistantBirthday` DATE NOT NULL,
  `Course_idCourse` INT NOT NULL,
  PRIMARY KEY (`idAssistant`, `Course_idCourse`),
  INDEX `fk_Assistant_Course1_idx` (`Course_idCourse` ASC) VISIBLE,
  CONSTRAINT `fk_Assistant_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Grade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Grade` (
  `Grade` INT NOT NULL,
  `Student_idStudent` INT NOT NULL,
  `Course_idCourse` INT NOT NULL,
  PRIMARY KEY (`Grade`, `Student_idStudent`, `Course_idCourse`),
  INDEX `fk_Grade_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  INDEX `fk_Grade_Course1_idx` (`Course_idCourse` ASC) VISIBLE,
  CONSTRAINT `fk_Grade_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grade_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registiration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Registiration` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Registiration` (
  `Student_idStudent` INT NOT NULL,
  `Course_idCourse` INT NOT NULL,
  `RegistrationID` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Semester_Year` INT NOT NULL,
  PRIMARY KEY (`Student_idStudent`, `Course_idCourse`, `RegistrationID`, `Semester_Year`),
  INDEX `fk_Student_has_Course_Course1_idx` (`Course_idCourse` ASC) VISIBLE,
  INDEX `fk_Student_has_Course_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  INDEX `fk_Registiration_Semester1_idx` (`Semester_Year` ASC) VISIBLE,
  CONSTRAINT `fk_Student_has_Course_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Course_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registiration_Semester1`
    FOREIGN KEY (`Semester_Year`)
    REFERENCES `mydb`.`Semester` (`Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
